### ISSUE TITLE
OpenCV 설치 사이트입니다.

### ISSUE THREAD

**Issue by minhub7** [oswswo123/Hustar_Group_4_TeamP#15]
https://medium.com/analytics-vidhya/how-to-install-opencv-for-visual-studio-code-using-ubuntu-os-9398b2f32d53

**Comment by bye-hwa** [comment]
좋아요 !

**Comment by oswswo123** [comment]
[](url)

**Comment by bye-hwa** [comment]
https://memostack.tistory.com/158

**Comment by minhub7** [comment]
https://webnautes.tistory.com/1158
